### ISSUE TITLE
Rename project to Corrosion

### ISSUE THREAD

**Issue by AndrewGaspar** [AndrewGaspar/corrosion#38]
- [ ] Change crate, module, and library names
- [x] Change the GitHub project name
- [x] Update README
- [x] Change function names

**Comment by ratijas** [comment]
Hey, @AndrewGaspar. I wonder, what the project was named back then, and why this issue is still opened?

**Comment by AndrewGaspar** [comment]
It used to be called "cmake-cargo". There are a bunch of CMake variable names that are still `CMAKE_CARGO_*`. Haven't gotten around to cleaning all of them up yet.

**Comment by ratijas** [comment]
Ah, "cmake-cargo".  I think I could recall hearing that name long time ago.

> There are a bunch of CMake variable names that are still `CMAKE_CARGO_*`

~IIRC, custom variable names are not allowed to start with `CMAKE_`. Which is probably the reason why they actually start with underscore-prefixed `_CMAKE_CARGO_*`.~ Both (underscored and not) variants are reserved per [cmake-variables(7)](https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html) documentation. If you don't mind, I'll give it a shot.
