### ISSUE TITLE
How to use cross compiling for Android?

### ISSUE THREAD

**Issue by lucaszanella** [AndrewGaspar/corrosion#45]
I decided to give a new try to this project, however, how is it possible to use cross compiling if the required CMake version for corrosion is 3.12 but Android's max available CMake is 3.10.2?

**Comment by AndrewGaspar** [comment]
Oh, I haven't heard of this issue. Can you expand on this? Is there any reason you can't use a newer CMake that doesn't come with the Android SDK?

**Comment by AndrewGaspar** [comment]
Check out the documentation for the Android NDK for using a newer CMake version: https://developer.android.com/studio/projects/install-ndk#vanilla_cmake

Let me know if that helps.

**Comment by AndrewGaspar** [comment]
I was working on improving the cross-compilation for Android experience last night, btw. I added some code to select the correct Rust target-triple when cross-compiling for Android - I'll try to merge that in soon.

I'm hitting an issue - if you are building an executable with Cargo, the final link fails. There must be some set of link arguments specified by the Android toolchain I need to apply when building an executable with cargo. I should probably be doing this anyway to make sure CMake specified link args are respected. If you do the final link with a C or C++ executable, then you should be fine. Of course, this breaks building shared libraries. I I intend to figure out what's going on.

**Comment by AndrewGaspar** [comment]
I figured out what was broken... Working on a fix.

**Comment by AndrewGaspar** [comment]
@lucaszanella There are some fixes in the latest develop branch. The README has also been updated to document cross-compiling for Android. Let me know if you have any questions. I apologize, I don't have a vested interest in cross-compiling for Android, so there may be issues beyond my basic test of just building Corrosion and the examples for Android.

**Comment by lucaszanella** [comment]
Thank you. Currently I broke some things on my app, gonna fix them and then try your suggestions!
