### ISSUE TITLE
Unable to install to standard location /usr/local

### ISSUE THREAD

**Issue by humenda** [AndrewGaspar/corrosion#52]
When installing CMake using the instructions from the README, Corrosion is installed to `/usr/local/Corrosion` on a GNU/`inux system. However, the install prefix should be /usr/local so that `FindPackage` discovers the package configuration.

**Comment by AndrewGaspar** [comment]
At some point I'll grok the CMake ["Search Procedure"](https://cmake.org/cmake/help/latest/command/find_package.html?highlight=find_package#search-procedure) for `find_package`! I'll take a look.

**Comment by AndrewGaspar** [comment]
Maybe I did grok it correctly...

`find_package(Corrosion)` works for me out of the default install path (`/usr/local/Corrosion`). What version of CMake are you using?

**Comment by humenda** [comment]
I'm using cmake 3.18.1. The CMakeLists:

```
```
find_package(Corrosion REQUIRED)
add_crate(Cargo.toml)
```

Output (paths changed)

```
-- Rust Toolchain: stable-x86_64-unknown-linux-gnu
-- Found Rust: $HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc (found version "1.46.0") 
No such file or directory
CMake Error at extern/corrosion/cmake/Corrosion.cmake:200 (message):
  corrosion-generator failed: 1
Call Stack (most recent call first):
  src/[…]/CMakeLists.txt:5 (add_crate)


-- Configuring incomplete, errors occurred!
```

**Comment by humenda** [comment]
I installed Corrosion with commit efd97c0c4fd2bc6520b015198f36e76cb90 on
Debian buster 10 to /usr/local/Corrosion (default path).

My MWE:

```cmake
cmake_minimum_required(VERSION 3.13)
project(mwe)
find_package(Corrosion REQUIRED)
add_crate(Cargo.toml)
add_executable(mwe)
target_link_libraries(mwe PRIVATE mwe_back)
target_sources(mwe PRIVATE main.c)
```

```
$ mkdir build && cd build && cmake ..

```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/lib/cmake/Corrosion/CorrosionConfig.cmake:38 (include):
  include could not find load file:

    Corrosion
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


CMake Error at CMakeLists.txt:5 (add_crate):
  Unknown CMake command "add_crate".


-- Configuring incomplete, errors occurred!
See also "[…]/mwe/build/CMakeFiles/CMakeOutput.log".
```

As a side note, unrelated to this issue: when using Corrosion as a submodule
or when invoking make install, there's some work done iwithout any message. My
experience is that this irritates users, maybe a message indicating that work
is being done would help.

**Comment by AndrewGaspar** [comment]
I can't reason about why CorrosionConfig.cmake would be at `/usr/local/lib/cmake/Corrosion/CorrosionConfig.cmake` - it should be at `/usr/local/Corrosion/lib/cmake/Corrosion/CorrosionConfig.cmake`. This is what the install call looks like for it:
```cmake
    install(
        FILES
            ${CMAKE_CURRENT_BINARY_DIR}/CorrosionConfig.cmake
            ${CMAKE_CURRENT_BINARY_DIR}/CorrosionConfigVersion.cmake
        DESTINATION Corrosion/lib/cmake/Corrosion
    )
```

Did you move files around when you were having issues?

I made a note about outputting information about bootstrapping corrosion-generator when using Corrosion as a submodule - let me know if this is what you were looking for: https://github.com/AndrewGaspar/corrosion/issues/55

Not sure what you mean about there being work done without a message when invoking "make install". Could you expand?

**Comment by humenda** [comment]
That was totally my bad, my MWE works now. Thanks!
