### ISSUE TITLE
Selectively import crates

### ISSUE THREAD

**Issue by AndrewGaspar** [AndrewGaspar/corrosion#57]
There should be a way to filter the imported crates from a workspace.

Something like:
```cmake
corrosion_import_crate(
    MANIFEST_PATH Cargo.toml
    CRATES foo)
```

cc @ogoffart

**EDIT:** Additionally, corrosion_import_crate should only import the crates in the target manifest, not for the whole workspace.

**Comment by AndrewGaspar** [comment]
@ogoffart, RE: https://github.com/AndrewGaspar/corrosion/issues/56#issuecomment-704287757

I don't think there's anything I can do about importing a sub-part of a workspace. In fact, what I might do is just fail out if you try to import a member of a workspace and require that you import the root crate.

**Comment by ogoffart** [comment]
Thanks for filling the issue.

Intuitively, i would have thought that importing a sub-part of a workspace would only import the lib from that specific Cargo.toml.
If that's not possible, having a `CRATES foo bar` to filter the target that i'm interested in would work just fine as well.

**Comment by AndrewGaspar** [comment]
Yeah, that's just the way Cargo works - it will look up in the directory structure to find the "root" crate, and then use that manifest instead. I find it kind of surprising, too, but I can see why they'd want that behavior.

**Comment by AndrewGaspar** [comment]
Well, maybe I should be more precise on that - it will only build the crates in the sub-manifest, even though it will operate in the _context_ of the root crate.

Maybe with that framing it should just import the crates from the sub-crate...

**Comment by AndrewGaspar** [comment]
OK, perhaps I'll only import crates from the target crate, even if it's not the root crate. :P

**Comment by ogoffart** [comment]
Hi Andrew, 
Are you currently working on this?
If not, i would like to help and try to contribute, as this is currently an important feature for the project i'm working on.

Also, when selecting specific crates, i would want to be able to choose features, but the `CRATES` syntax would not allow that.

Imagine I want to build two crates and i want to specify some features.
I can think of a few options:

1. Have a `CRATE` and feature option

```cmake
corrosion_import_crate(
    MANIFEST_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Cargo.toml 
    CRATE foo 
    FEATURES ffi
)
corrosion_import_crate(
    MANIFEST_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Cargo.toml 
    CRATE bar 
    FEATURES ${BAR_FEATURES})
)
```

2. If possible, select the crates using a specific Cargo.toml 

```cmake
corrosion_import_crate(
    MANIFEST_PATH ${CMAKE_CURRENT_SOURCE_DIR}/foo/Cargo.toml 
    FEATURES ffi
)
corrosion_import_crate(
    MANIFEST_PATH ${CMAKE_CURRENT_SOURCE_DIR}/bar/Cargo.toml 
    FEATURES ${BAR_FEATURES})
)
```

3. Or maybe something like this could work?
```cmake
corrosion_import_crate(
    MANIFEST_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Cargo.toml 
    CRATES foo bar 
)
set_property(TARGET foo CORROSION_FEATURES "ffi")
set_property(TARGET bar CORROSION_FEATURES ${BAR_FEATURES})
```

What would you think is best?

**Comment by AndrewGaspar** [comment]
Go ahead and give it a shot! I'd love to have more hands on this.

In my opinion, we could do both 1 and 3 - I think 1 is cleaner and probably sufficient for most cases, but I don't see any reason we couldn't make `CORROSION_FEATURES` a target property too. Be careful when implementing it - you'll need to use generator expressions to apply the features in the build.

**Comment by AndrewGaspar** [comment]
Ah, I'm changing my mind again. Maybe it would be cleaner to just ditch the `CRATES` syntax and only implement the crate described by the manifest. So 2 and 3. I think that's my final answer.

**Comment by ratijas** [comment]
With #67 rolled out, this issue is half-resolved. The other half is selecting features. Some ideas were outlined, but at this point the path forward is kinda fuzzy, and no implementation exists. Is that correct?

**Comment by kwek20** [comment]
@ratijas Im actually working on this right now

**Comment by tronical** [comment]
> With #67 rolled out, this issue is half-resolved. The other half is selecting features. Some ideas were outlined, but at this point the path forward is kinda fuzzy, and no implementation exists. Is that correct?

With #108 having landed in the main branch, is there anything left in this issue?
