### ISSUE TITLE
Toolchain resolution breaks when default toolchain is overridden

### ISSUE THREAD

**Issue by EliaGeretto** [AndrewGaspar/corrosion#81]
### Steps to reproduce:
- Create `build` folder.
- Run `rustup override set nightly` in it.
- Try building the project.

### Result:
```
CMake Error at /home/egeretto/XXX/build/_deps/corrosion-src/cmake/FindRust.cmake:166 (find_program):
  Could not find Rust_CARGO_CACHED using the following names: cargo
Call Stack (most recent call first):
  /home/egeretto/XXX/build/_deps/corrosion-src/cmake/Corrosion.cmake:11 (find_package)
  /home/egeretto/XXX/build/_deps/corrosion-src/CMakeLists.txt:39 (include)
```

### Cause:
When running in a folder with an overridden toolchain, the output of `rustup toolchain list --verbose` looks like the following:
```
stable-x86_64-unknown-linux-gnu (default)	/home/egeretto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (override)	/home/egeretto/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
```

However, the following regex does not take the `(override)` into account:
https://github.com/AndrewGaspar/corrosion/blob/2e4c62c9f001487b485c2f8c923dba348607b41c/cmake/FindRust.cmake#L96

**Comment by AndrewGaspar** [comment]
Thank you for pointing exactly to the line at issue! I should probably go look at exactly what rustup outputs for this command so I can see if there's anything else unexpected that it does.

I've been busy, but I'll try to fix this soonish. Happy to accept PRs, too.
